Upgraded to the following software versions:     CMake 3.21.1     GCC 11.2.0     Clang 12.0.1     JasPer 2.0.33     CGAL 5.3     Aristotle 3.0.38     Catch2 2.13.7     Vim LSP 7ba553effb021293c9ff5176b91e76da71797825     Vim Asyncomplete 6c653c3f8f1c1cf7a34522c9555d5160f36d29ee     GitHub CLI 1.14.0     Fmtlib 8.0.1
Added a CLI option to the sde_install_ycm to skip cleanup.
Removed some commands from the vim configuration file generated by the
sde_install_vimlsp script.

diff --git a/bin/sde_install_ycm b/bin/sde_install_ycm
--- a/bin/sde_install_ycm
+++ b/bin/sde_install_ycm
@@ -33,6 +33,14 @@ panic()
 	exit 1
 }
 
+perform_cleanup()
+{
+	if [ -n "$tmp_dir" -a -d "$tmp_dir" ]; then
+		rm -rf "$tmp_dir" || \
+		  echo "warning: cannot remove temporary directory $tmp_dir"
+	fi
+}
+
 usage()
 {
 	echo "BAD USAGE: $@"
@@ -56,14 +64,18 @@ user=$(whoami) || panic "cannot get user name"
 host=$(hostname) || panic "cannot get host name"
 cur_dir=$(pwd) || panic "cannot get current directory"
 
+tmp_dir_template="${SDE_TMPDIR:-/tmp}/sde_install_ycm-$user-$host-XXXXXXXX"
+
 version=master
 install_dir=
-tmp_dir="/tmp/sde_install_ycm-$user@$host-$$"
 libclang=
 verbose=0
+cleanup=1
 
-while getopts d:v:l:V opt; do
+while getopts Cd:v:l:V opt; do
 	case "$opt" in
+	C)
+		cleanup=0;;
 	d)
 		install_dir="$OPTARG";;
 	v)
@@ -91,6 +103,13 @@ fi
 # This will help to increase the likelihood that the installed software
 # will be accessible by all users.
 umask 022
+
+tmp_dir=$(mktemp -d "$tmp_dir_template") || \
+  panic "cannot create temporary directory"
+echo "temporary directory: $tmp_dir"
+if [ "$cleanup" -ne 0 ]; then
+	trap perform_cleanup EXIT
+fi
 
 top_dir="$tmp_dir/ycm-$version"
 
@@ -151,4 +170,5 @@ fi
 cp "$example_file" "$misc_dir/ycm_extra_conf.py" || \
   panic "cannot copy file"
 
-rm -rf "$tmp_dir"
+echo "temporary directory: $tmp_dir"
+echo "need to install watchdog now"
