Changed the sde_install_jasper script to obtain JasPer from GitHub.

diff --git a/bin/sde_install_jasper b/bin/sde_install_jasper
--- a/bin/sde_install_jasper
+++ b/bin/sde_install_jasper
@@ -29,6 +29,14 @@ panic()
 	exit 1
 }
 
+perform_cleanup()
+{
+	if [ -n "$tmp_dir" -a -d "$tmp_dir" ]; then
+		rm -rf "$tmp_dir" || \
+		  echo "warning: cannot remove temporary directory $tmp_dir"
+	fi
+}
+
 usage()
 {
 	echo "BAD USAGE: $@"
@@ -51,9 +59,12 @@ cur_dir=$(pwd) || panic "cannot get current directory"
 version=
 install_dir=
 build_doc=1
+cleanup=1
 
-while getopts d:v:o: opt; do
+while getopts d:v:o:C opt; do
 	case "$opt" in
+	C)
+		cleanup=0;;
 	d)
 		install_dir="$OPTARG";;
 	v)
@@ -82,16 +93,27 @@ if [ -z "$version" ]; then
 	usage "no version specified"
 fi
 
+abs_install_dir="$(readlink -f "$install_dir")" || \
+  panic "readlink failed"
+install_dir="$abs_install_dir"
+
 # Set the user file-creation mask to allow read and execute permissions
 # for the group and others.
 # This will help to increase the likelihood that the installed software
 # will be accessible by all users.
 umask 022
 
-tmp_dir="/tmp/sde_install_jasper-$user@$host-$$"
+url="https://github.com/jasper-software/jasper/archive/version-$version.tar.gz"
+
+tmp_dir_template="/tmp/sde_install_jasper-$user@$host-XXXXXXXX"
+
+tmp_dir=$(mktemp -d "$tmp_dir_template") || \
+  panic "cannot create temporary directory"
+if [ "$cleanup" -ne 0 ]; then
+	trap perform_cleanup EXIT
+fi
 src_dir="$tmp_dir"
 build_dir="$tmp_dir/tmp_cmake"
-url="http://www.ece.uvic.ca/~mdadams/jasper/software/jasper-$version.tar.gz"
 
 for dir in "$tmp_dir" "$build_dir"; do
 	mkdir -p "$dir" || \
@@ -124,8 +146,11 @@ fi
 make_opts=()
 make_opts+=(-j4)
 
-(cd "$build_dir" && make "${make_opts[@]}") || panic "make failed"
+(cd "$build_dir" && make "${make_opts[@]}") || \
+  panic "make failed"
 
-(cd "$build_dir" && make install) || panic "make install failed"
+(cd "$build_dir" && make install) || \
+  panic "make install failed"
 
-rm -rf "$tmp_dir" || panic "cannot remove temporary directory $tmp_dir"
+rm -rf "$tmp_dir" || \
+  panic "cannot remove temporary directory $tmp_dir"
